name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install npm@7
        run: npm i -g npm@7
      - name: Install
        run: npm ci --prefer-offline
      - name: Alex
        run: npm run alex
